In [1]:
import pandas as pd
import numpy as np

In [4]:
myarr = np.array([[3,6,37,7]], np.int64)

In [5]:
myarr[0,1]

6

In [6]:
myarr.shape

(1, 4)

In [7]:
myarr.dtype

dtype('int64')

In [8]:
myarr[0,1] = 45

In [9]:
myarr

array([[ 3, 45, 37,  7]], dtype=int64)

# Array Creation: Conversion from other python structures

In [10]:
listarray = np.array([[1,2,3], [5,8,5], [0,3,1]])

In [11]:
listarray

array([[1, 2, 3],
       [5, 8, 5],
       [0, 3, 1]])

In [12]:
listarray.dtype

dtype('int32')

In [13]:
listarray.shape

(3, 3)

In [14]:
listarray.size

9

In [15]:
np.array({34,23,23})

array({34, 23}, dtype=object)

# Intrinsic numpy creation objects

In [16]:
zeros = np.zeros((2,5))

In [17]:
zeros

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [18]:
zeros.dtype

dtype('float64')

In [19]:
rng = np.arange(15)

In [20]:
rng

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [23]:
lspace = np.linspace(1,4,4)

In [24]:
lspace

array([1., 2., 3., 4.])

In [25]:
emp = np.empty((4,6))

In [26]:
emp

array([[7.56587584e-307, 1.37961302e-306, 1.05699242e-307,
        9.37003421e-312, 0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000, 0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000,             nan, 0.00000000e+000,
        0.00000000e+000, 0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 2.22523207e-306,
        6.23059726e-307, 1.33511562e-306, 6.89805151e-307]])

In [27]:
emp_like = np.empty_like(lspace)

In [28]:
emp_like

array([1., 2., 3., 4.])

In [29]:
ide = np.identity(45)

In [30]:
ide

array([[1., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 1.]])

In [31]:
ide.shape

(45, 45)

In [32]:
arr = np.arange(99)

In [33]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [34]:
arr.reshape(3,33)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
        49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64,
        65],
       [66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
        98]])

In [35]:
arr.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [37]:
arr.shape

(99,)

In [38]:
x = [[1,2,3], [4,5,6], [7,1,0]]

In [39]:
ar = np.array(x)

In [40]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [41]:
ar.sum(axis=0)

array([12,  8,  9])

In [42]:
ar.sum(axis=1)

array([ 6, 15,  8])

In [43]:
ar.T

array([[1, 4, 7],
       [2, 5, 1],
       [3, 6, 0]])

In [44]:
ar.flat

In [46]:
for item in ar.flat:
    print(item)

1
2
3
4
5
6
7
1
0


In [47]:
ar.ndim

2

In [48]:
ar.size

9

In [49]:
ar.nbytes

36

In [50]:
one = np.array([1,3,4,634,2])

In [52]:
one.argmax()      # returns the index of the highest value 

3

In [54]:
one.argmin()      # returns the index of the lowest value

0

In [56]:
one.argsort()     # returns the indices of the elment which are in a sorted way

array([0, 4, 1, 2, 3], dtype=int64)

In [57]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [58]:
ar.argmin()

8

In [59]:
ar.argmax()

6

In [60]:
ar.argmax(axis=0)

array([2, 1, 1], dtype=int64)

In [61]:
ar.argmax(axis=1)

array([2, 2, 0], dtype=int64)

In [62]:
ar.argsort(axis=1)

array([[0, 1, 2],
       [0, 1, 2],
       [2, 1, 0]], dtype=int64)

In [63]:
ar.argsort(axis=0)

array([[0, 2, 2],
       [1, 0, 0],
       [2, 1, 1]], dtype=int64)

In [64]:
ar.ravel()

array([1, 2, 3, 4, 5, 6, 7, 1, 0])

In [65]:
ar.reshape((9,1))

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [1],
       [0]])

In [66]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [67]:
ar2 = np.array([[1, 2, 1],
       [4, 0, 6],
       [8, 1, 0]])

In [68]:
ar + ar2

array([[ 2,  4,  4],
       [ 8,  5, 12],
       [15,  2,  0]])

In [69]:
ar * ar2

array([[ 1,  4,  3],
       [16,  0, 36],
       [56,  1,  0]])

In [70]:
np.sqrt(ar)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.64575131, 1.        , 0.        ]])

In [71]:
ar.sum()

29

In [72]:
ar.max()

7

In [73]:
ar.min()

0

In [74]:
np.where(ar > 5)

(array([1, 2], dtype=int64), array([2, 0], dtype=int64))

In [75]:
type(np.where(ar > 5))

tuple

In [77]:
np.count_nonzero(ar)  # returns the count of elements which are non-zero

8

In [78]:
np.nonzero(ar)

(array([0, 0, 0, 1, 1, 1, 2, 2], dtype=int64),
 array([0, 1, 2, 0, 1, 2, 0, 1], dtype=int64))

In [79]:
ar[1,2] = 0

In [80]:
np.nonzero(ar)


(array([0, 0, 0, 1, 1, 2, 2], dtype=int64),
 array([0, 1, 2, 0, 1, 0, 1], dtype=int64))

In [81]:
import sys

In [83]:
py_ar = [0,4,55,2]

In [84]:
np_ar = np.array(py_ar)

In [85]:
sys.getsizeof(1) * len(py_ar)

112

In [86]:
np_ar.itemsize * np_ar.size

16

In [87]:
np_ar.tolist()

[0, 4, 55, 2]